### ISSUE TITLE
Cathy Introduction

### ISSUE THREAD

**Issue by Cathi0n** [stat545ubc-2023/collaborative-group15#10]
Hi everyone! I'm Cathy. I'm a first year M.Sc. Biochemistry student.

I can't really think of any truths or lies right now so I'll just say that my hobbies include drawing or video games. My favourite food is probably sushi! It's nice to meet everyone!

@kokowaahmax @SidneySaint @SteveLiu1723

**Comment by SteveLiu1723** [comment]
Do u play Pokemon?

**Comment by kokowaahmax** [comment]
We can play league of legend. ;)

**Comment by SidneySaint** [comment]
Let's get some sushi <3
