### ISSUE TITLE
Intro to Sidney

### ISSUE THREAD

**Issue by SidneySaint** [stat545ubc-2023/collaborative-group15#11]
Hey all! Intro to me: I'm originally from Ontario and just started my MSc in the ExMed Program. 

2 Truths 1 lie:
1. I speak Spanish.
2. I used to teach 10th grade.
3. I have never used github before.

@Cathi0n @kokowaahmax @SteveLiu1723

**Comment by Cathi0n** [comment]
Hi Sidney! I'm also from Ontario. I think that your lie is number 1

**Comment by SteveLiu1723** [comment]
I think the first one is lie maybe?

**Comment by kokowaahmax** [comment]
Hi, nice to meet you. I guess the first one is a lie.
