### ISSUE TITLE
Intro to Max 

### ISSUE THREAD

**Issue by kokowaahmax** [stat545ubc-2023/collaborative-group15#8]
2 truth and 1 lie

1. I am 6 feet 1
2. I lose 20kg in a month
3. I did sky-diving

Which one is lie? @SidneySaint @Cathi0n @SteveLiu1723

**Comment by SidneySaint** [comment]
Not really an intro ---- but Hi Xin Wang! I hope 2 is the lie....

**Comment by Cathi0n** [comment]
I think that number 2 is a lie. Sky-diving sounds really fun!

**Comment by kokowaahmax** [comment]
Hahah the third one is actually the lie ;)

**Comment by kokowaahmax** [comment]
@SteveLiu1723 Hi Zefan, can you response to my intro of 2 truth and a lie?

**Comment by SteveLiu1723** [comment]
Even though I know that the third one is the answer, I would still choose the 2nd. That's amazing!
