### ISSUE TITLE
Intro to Steve

### ISSUE THREAD

**Issue by SteveLiu1723** [stat545ubc-2023/collaborative-group15#9]
Hi everyone I am Zefan Liu(Steve). I am a new master student of department of statistics

2 truths and 1 lie

1. I am going to Coldplay's concert on Sept 22nd.

2. I work out.

3. I am on diet.

@Cathi0n @kokowaahmax @SidneySaint

**Comment by kokowaahmax** [comment]
nice  way to know you, i believe 2 is the lie.

**Comment by Cathi0n** [comment]
Nice to meet you! I think your lie is number 3 possibly?

**Comment by SteveLiu1723** [comment]
The third one is lie.

**Comment by SidneySaint** [comment]
If 1 isnt the lie I'm jealous! Guessing 3 ?

**Comment by kokowaahmax** [comment]
Steve (Zefan) introduced him to us, close as completed :)
